# Generated by Django 4.2 on 2023-07-21 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title Description')),
                ('text', models.TextField(max_length=500, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Brief',
                'verbose_name_plural': 'Briefs',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('picture', models.FileField(upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('severity', models.IntegerField(choices=[(1, 'Bad'), (2, 'Terrible'), (3, 'Cataclysmic')], default=1, verbose_name='Severity')),
                ('briefs', models.ManyToManyField(related_name='briefs', to='response.brief')),
                ('emergency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='auth.group')),
            ],
            options={
                'verbose_name': 'Emergency Response',
                'verbose_name_plural': 'Emergency Responses',
            },
        ),
    ]
