# Generated by Django 4.2 on 2023-07-30 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='respondents',
            field=models.ManyToManyField(related_name='experts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brief',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='files', to='response.file'),
        ),
        migrations.AddField(
            model_name='brief',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
