# Generated by Django 4.2 on 2023-07-15 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='respondents',
            field=models.ManyToManyField(related_name='experts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brief',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='pictures', to='response.picture'),
        ),
        migrations.AddField(
            model_name='brief',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos', to='response.video'),
        ),
    ]
