# Generated by Django 4.2 on 2023-07-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
    ]
