# Generated by Django 4.2 on 2023-07-24 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('response', '0003_rename_picture_picture_file_rename_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='emergency_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='auth.group'),
        ),
    ]
