# Generated by Django 4.2 on 2023-07-25 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0004_alter_emergency_emergency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='brief',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='brief',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='brief',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='files', to='response.file'),
        ),
    ]
