# Generated by Django 4.2 on 2023-07-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0005_file_remove_brief_pictures_remove_brief_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='briefs',
            field=models.ManyToManyField(blank=True, related_name='briefs', to='response.brief'),
        ),
    ]
