# Generated by Django 4.2 on 2023-07-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('response', '0006_alter_emergency_briefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='emergency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='auth.group'),
        ),
    ]
