# Generated by Django 4.2 on 2023-04-03 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'ROOT'), ('2', 'RESPONSE')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadEvent',
            fields=[
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.ManyToManyField(to='event.role')),
            ],
        ),
    ]
