# Generated by Django 4.2 on 2023-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_role_threadevent_roles_role_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role',
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='threadevent',
            name='id',
            field=models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
