# Generated by Django 4.2 on 2023-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_lasteventtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='response_time',
            field=models.DecimalField(decimal_places=3, default=3.958915, max_digits=12),
            preserve_default=False,
        ),
    ]
