# Generated by Django 4.2 on 2023-08-03 07:02

from django.db import migrations
import eResponse.user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', eResponse.user.managers.UserManager()),
            ],
        ),
    ]
