# Generated by Django 4.2 on 2023-07-31 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_title_certification_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
