# Generated by Django 4.2 on 2023-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_type', models.CharField(default='bearer', editable=False, max_length=6)),
                ('access_token', models.CharField(db_index=True, editable=False, max_length=666, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Token',
            },
        ),
    ]
